name: Build & Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        env:
          GOOS: linux
        run: |
          go build -o server main/main.go
          ls
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: go_web_project
          path: /home/runner/work/go_web_project/go_web_project/server

      - name: Upload dockerFile
        uses: actions/upload-artifact@v1
        with:
          name: Dockerfile
          path: /home/runner/work/go_web_project/go_web_project/main/Dockerfile
      - name: Upload config
        uses: actions/upload-artifact@v1
        with:
          name: config
          path: /home/runner/work/go_web_project/go_web_project/main/config
  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: go_web_project
          path: server
      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: Dockerfile
          path: Dockerfile
      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: config
          path: .
      - name: build Image
        run: |
          mv server/server Dockerfile/server
          ls
          docker build -t killerqueen07/go_web_project Dockerfile
          docker login --username=killerqueen07 --password=CZL20010821
          docker push killerqueen07/go_web_project
