name: Build & Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        env:
          GOOS: linux
        run: |
          go build -o server main/main.go 
          pwd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: go_web_project
          path: /home/runner/work/go_web_project/go_web_project
  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: go_web_project
          path: /home/runner/work/go_web_project/go_web_project/server

      - name: build Image
        run: |
          docker login --username=${{secrets.ALI_DOCKER_HUB_USN}} --password=${{secrets.ALI_DOCKER_HUB_PWD}}
          docker build -t . --tag killerqueen07/server
          docker push killerqueen07/server
